export const WORKSPACE_CREATE_REQUEST = "WORKSPACE_CREATE_REQUEST";
export const WORKSPACE_CREATE_SUCCESS = "WORKSPACE_CREATE_SUCCESS";
export const WORKSPACE_CREATE_FAIL = "WORKSPACE_CREATE_FAIL";

export const GET_ALL_WORKSPACE_REQUEST = "GET_ALL_WORKSPACE_REQUEST";
export const GET_ALL_WORKSPACE_SUCCESS = "GET_ALL_WORKSPACE_SUCCESS";
export const GET_ALL_WORKSPACE_FAIL = "GET_ALL_WORKSPACE_FAIL";
export const WORKSPACE_CREATE_RESET = "WORKSPACE_CREATE_RESET"